package am.itspace.car_rental_common.entity;

public enum Category {
    SEDAN, COUPE, SPORT_CAR, STATION_WAGON, HATCHBACK, CONVERTIBLE, SUV, MINIVAN, PICKUP, JEEP, ELECTRIC, CUV, SPYDER, HOT_HATCH, LIMOUSINE, UTE, PONY_CAR, SPORTS_SEDAN
}
